### ISSUE TITLE
Plans for search?

### ISSUE THREAD

**Issue by briannhinton** [justinwalsh/daux.io#18]
Curious if search is in the future roadmap?

**Comment by laxa88** [comment]
Hi, I implemented a search bar that quick searches the nav-list on the left using jquery. I've made a pull request. I hope it helps some people in need of this simple feature. If the code is inefficient or not practical, I would also appreciate critique/feedback so I can learn. Thank you.

**Comment by Faldrian** [comment]
Hm... I want to use daux for generating documentation viewable by the clients of the company I work for. Search is a must - so I will have my take on adding search. ;)

I think something like this should work:

1. Create a keywords-to-page index that is refreshed when the server is started / when files are changed (I have to dig into how daux.io works to be sure how to update the index)
2. Let this index be a JSON or something client-parsable (because I want those docs to work offline just fine...). I may do the search on the server instead if I can't get the JSON-index reasonably small...
3. once you search something and there is a list of pages which includes matches you can go to that page.
4. the search-term is added to the url-hash, so a clientside JS-script can highlight the terms on page-load

That's the plan... sounds reasonable?

**Comment by onigoetz** [comment]
Search has been added for generated documentations, live version doesn't have that feature
