### ISSUE TITLE
Transitioning to SemVer and publishing releases

### ISSUE THREAD

**Issue by dkisselev** [justinwalsh/daux.io#214]
As a followup to #211, I think we should start tagging releases and uploading complete pacages (and also remove parsedown from our version control)

My question is, does anyone see any particular issues or bugs that need to be fixed before we should publish a 1.0.0? @Gautham's refactor closed almost every single ticket in that milestone. NGinx support  isn't really related to daux itself (we use a very common rewrite settings, so it's not too hard to find an equivalent example that works there)

**Comment by onigoetz** [comment]
In the refactoring I made there is a new theme structure. Allowing to be overriden by any theme : create a file in `theme/your-theme/templates/` with the same name as the original theme and it will replace this part of the template.

I also put in common the less files for all 4 themes. so that only the minimum is overriden on theme change.
