### ISSUE TITLE
Combine Resources and Templates

### ISSUE THREAD

**Issue by holodyn** [justinwalsh/daux.io#303]
We could merge the templates and theme concepts into one.  The `default` or maybe `base` template is where we find everything for the core system.

````
/daux/templates/default/layout/
/daux/templates/default/partials/
/daux/templates/default/assets/
/daux/templates/default/assets/js/
/daux/templates/default/assets/css/
/daux/templates/default/assets/images/
/daux/templates/default/assets/less/
````

We then override the default files with customizations as needed within a theme.

````
/daux/templates/daux-blue/
/daux/templates/daux-blue/assets/css/
/daux/templates/daux-blue/assets/images/
/daux/templates/daux-blue/assets/less/
````

A theme handler can do a simple lookup:

````
$handler = new ThemeHandler( 'path_to_templates', 'daux-blue' );
$handler->getTemplate( 'content.php' );
````

Which would look within:

````
/daux/templates/daux-blue/content.php
/daux/templates/default/content.php
````

The same logic could work with assets.

````
$handler = new ThemeHandler( 'path_to_templates', 'daux-blue' );
$handler->addScriptAsset( 'jquery.plugin.xxx/plugin.js' );
````

Which would look within:

````
/daux/templates/daux-blue/assets/js/jquery.plugin.xxx/plugin.js
/daux/templates/default/assets/js/jquery.plugin.xxx/plugin.js
````

**Comment by onigoetz** [comment]
I don't understand a few things why you say :  The /libs/resources/themes folder should be moved. The ressources are not currently inside the libs folder.

Plus, the behaviour you explain already works today, inside your theme you can add a file that has the same name as the original template and this one will be loaded automatically.

But you're right, the structure could be improved and we could also overload resources. I wanted to change the structure like you described it so that the theme contains all resources, and not the other way around.

**Comment by holodyn** [comment]
Sorry - you are absolutely correct, I was typing that from memory and way off base, so scratch the /libs/ comment.

I wasn't aware that we could already overload the template files - so this is perfect. All we need to do is collapse templates and resources together and we're good.  Glad we're on the same page there.

**Comment by onigoetz** [comment]
No problem, the fault is on my part, I didn't write the documentation yet on how to override templates.

**Comment by onigoetz** [comment]
I close this as pull request #304 is underway
