### ISSUE TITLE
404 not found error while accessing directly using a webserver

### ISSUE THREAD

**Issue by janardhanwtc** [justinwalsh/daux.io#310]
Hello,

I've downloaded daux.io version and placed that in wamp server. When i run grunt it is working fine. But, when i try to run using wamp server, it is giving 404 error. But, when i include index.php in the url, then its working.

Ex: when i try to access http://localhost/daux.io-master/Examples, it is throwing 404 error. 

![404](https://cloud.githubusercontent.com/assets/2986244/9489267/71ec687c-4bfd-11e5-8b35-5fbdb4aa90ce.PNG)

But, if i include index.php like - http://localhost/daux.io-master/index.php/Examples, then it works. Same applies for all. 

![working](https://cloud.githubusercontent.com/assets/2986244/9489268/71ef35b6-4bfd-11e5-93dd-c484f116ce9b.PNG)

With grunt, it automatically adds that index.php to url. Can you please help me in solving this to get this work in server?

Thanks in advance.

**Comment by esphen** [comment]
What you are looking for is called **clean_urls**. It can be disabled in the config.json file to get behaviour like you see in grunt. Have a look at the [docs](http://daux.io/) , it is under the *Clean URLs* section.

The reason this is happening is probably because you have not enabled the rewrite module in your web server (wamp). The server would ordinarily redirect anything under daux.io-master to daux.io-master/index.php. If you enable this module and allow .htaccess files in your apache config with `AllowOverride All`, then it should work as advertised.

**Comment by janardhanwtc** [comment]
Thanks esphen, that worked. :)
