### ISSUE TITLE
Link to other Pages

### ISSUE THREAD

**Issue by benelang** [justinwalsh/daux.io#330]
Is there a possibility to link to another page of the documentation? If not, this would be a great feature!

**Comment by onigoetz** [comment]
Yes it is available :D 

It is available on the development branch (we cannot push to master because the production server runs automatically on master, which can't run recent PHP versions yet, BTW @justinwalsh  any news on that ?)

Here's the documentation : https://github.com/justinwalsh/daux.io/blob/development/docs/00_Getting_Started.md#internal-links

**Comment by justinwalsh** [comment]
@onigoetz I am going to be moving the site to a new server today. Which version of php should I target?

**Comment by onigoetz** [comment]
Technically, it works on PHP 5.4 but it would be better if you target 5.5 or 5.6 directly.

**Comment by justinwalsh** [comment]
I have moved the site to our new servers. Should be a little faster now :) Also running 5.6.x Thanks again @onigoetz for all your work helping to maintain Daux!

**Comment by onigoetz** [comment]
Awesome !

No problem I like this project and it is very useful for the documentations I need to write and maintain

**Comment by onigoetz** [comment]
BTW, I got a notification that the production deployment failed, it works fine on dev.daux.io but it seems the production is corrupted. is there a rights problem ?
