### ISSUE TITLE
Error when using ./generate

### ISSUE THREAD

**Issue by mmeineke** [justinwalsh/daux.io#354]
Hi,

when I am trying to generate the docs as html I get an error.
```
$ ./generate --format=html
```
Output:
```
Warning: require_once(vendor/autoload.php): failed to open stream: No such file or directory in /daux.io/generate on line 67

Fatal error: require_once(): Failed opening required 'vendor/autoload.php' (include_path='.:') in /daux.io/generate on line 67
```
Am I missing something?
When I change the line `require_once("vendor/autoload.php");` with the lines from the `index.php` (lines 78-85) everything is just fine.

**Comment by onigoetz** [comment]
Hello,

when using daux just after download it is recommended to use the command `./daux.phar` instead of `./generate`

daux.phar is a generated version that contains all dependencies.
whereas generate is just a launcher for the full version.

We should merge that somehow, or have `./generate` fallback to `daux.phar` automatically.
