### ISSUE TITLE
Live search with lunr.js

### ISSUE THREAD

**Issue by phsc** [justinwalsh/daux.io#359]
Currently it is only possible to activate search in static mode, but not in live mode.

By implementing [lunr.js](http://lunrjs.com/) (or something similar), it shoud be possible to activate search in live mode.

**Comment by onigoetz** [comment]
Hello,

Tipuesearch is similar to lunr.js in terms of final user features and both are not suited for use in live mode.

The search feature requires all documentation pages to be rendered in order to be processed. This would create too much pressure on the server if all the documentation pages need to be rendered on every search.

That's why we decide to not provide that feature in live mode
