### ISSUE TITLE
How to disable the index?

### ISSUE THREAD

**Issue by Overv** [justinwalsh/daux.io#368]
How do I simply show the first documentation page in the layout with the sidebar when the root of the site is loaded?

Currently I'm creating an empty dummy `index.md` file with an nginx rewrite rule to rewrite requests to `/` and `/index` to `/first_chapter_name`, but that seems like a hack. The empty index file is necessary, because otherwise daux treats the first chapter as the homepage contents.

**Comment by Overv** [comment]
Nevermind, I just realised you can use `"auto_landing": false` for that. Perhaps that should be added to the README.

**Comment by onigoetz** [comment]
Hello,

actually, it is already in the documentation : http://daux.io/Features/Landing_page

**Comment by Overv** [comment]
@onigoetz I know, but I was looking at the README instead because it has a complete overview of settings on a single page.

**Comment by onigoetz** [comment]
I don't want to put everything in the README, that would be a lot of options, I prefer to put what's really needed in the README and then point to the rest of the documentation

**Comment by zeigerpuppy** [comment]
I think there may be a bug in the html generator when `"auto_landing": false,`.
The live site navigation works properly but the static site get's a 404 because no `index.html` is found.

There are no build errors.  Browsing to a subdirectory works but the site link is then broken because it redirects to the non-existent landing page.

**Comment by zeigerpuppy** [comment]
this can be made functional by having a _index.md page in the docs folder and making it blank
