### ISSUE TITLE
Adding a simple login system

### ISSUE THREAD

**Issue by nathanjisaac** [justinwalsh/daux.io#37]
Is their a way to add an optional simple login system to this documentation web app? I would love to use this for my company web app documentation, however, it has some sensitive information that I need to keep secure. Thanks for your suggestions.

**Comment by onigoetz** [comment]
@justinwalsh @dkisselev Anything new on this ? do we want to add this or do we focus on the generation features and let people use a .htaccess ?

**Comment by JayHoltslander** [comment]
+1 for login system. But will use .htaccess until then.

**Comment by abhayghatpande** [comment]
Does anyone have any ideas regarding how this could be implemented? I could try my hand at it. We use GApps for Work, so ideally if we could use the Google OAuth mechanism, that would be great. But I'm willing to live with a simpler/different one.

On another note, how much faith can I put in the .htaccess mechanism? If one has a strong password, is it dependable? Thanks!

**Comment by onigoetz** [comment]
Hi, .htpasswd/.htaccess works just fine, you can add as many users as you want and it's handled by apache/nginx just fine

**Comment by abhayghatpande** [comment]
Thanks. I'm using Lighttpd, and did implement the .htpasswd mechanism, along with SSL certificates from Letsencrypt. It's working, but there is a perception among colleagues that somehow .htaccess is not as secure as "other" methods.

**Comment by dkisselev** [comment]
Yeah, I can understand that sentiment.

I think .htpasswd seems insecure mostly because it's so simple, it's an ugly popup dialog that you can't customize all that much.

You could argue that htpasswd can be more secure mechanisms are hardcoded into the web server, which 

a) isn't usually updated as much as the application, and 
b) has fewer moving parts

A PHP auth implementation would have databases, hashing libraries, our code, your code, etc. that could all fail, but most projects just take on that risk because you need that flexibility with authenticating users.

The biggest gotchas to watch out for with htpasswd are that your (hashed) passwords are easy to get at from a single file on the server and that you're less likely to keep them secure (ie, not making a unique password per user, and not keeping that list updated as users come and go)

That being said, if you guys have an LDAP server available for your workplace, you can tie basic auth into it for better password control: https://www.cs.rit.edu/~gjv2098/ldap_auth_howto.html

**Comment by abhayghatpande** [comment]
Thanks for that @dkisselev 
I'll keep those points in mind. I've also taken most precautions advised.
Will live with .htaccess for now.

**Comment by onigoetz** [comment]
Closing this issue as we move the project to an organization: https://github.com/dauxio/daux.io, the packagist package name is now [`daux/daux.io`](https://packagist.org/packages/daux/daux.io) and we even have a [Docker image](https://hub.docker.com/r/daux/daux.io/).

If you are still interested by that feature, please open a new issue in the organization and we'll look into it.
