### ISSUE TITLE
Processor.php line 177

### ISSUE THREAD

**Issue by nadilas** [justinwalsh/daux.io#375]
Hi there,

after downloading the repo and installing the dependencies. I configured nginx to start listening. But I'm stuck with the following error:
`PHP Fatal error:  Can't use method return value in write context in phar:///opt/daux.io/daux.phar/libs/Format/HTML/ContentTypes/Markdown/TOC/Processor.php on line 177
`
No matter if I use ./generate or via the web server, I can't seem to get past it.

Have you ever had something similar?

**Comment by onigoetz** [comment]
No, this error doesn't look familiar to me,

Can you try to run with the local version of the code ?

```
rm daux.phar
composer install 
```

Maybe the version currently bundled is outdated.

**Comment by nadilas** [comment]
Thanks! Using ./serve it is working great! 👍 
How would I go about regenerating the phar file so that nginx can access the page?

**Comment by onigoetz** [comment]
You can use the command bin/compile to regenerate the .phar

Get Outlook for iOS




On Wed, Jun 8, 2016 at 12:45 PM +0200, "nadilas" <notifications@github.com> wrote:












Thanks! Using ./serve it is working great! 👍 

How would I go about regenerating the phar file so that nginx can access the page?

**Comment by nadilas** [comment]
Thanks!
