### ISSUE TITLE
How to enable search in live mode

### ISSUE THREAD

**Issue by zeigerpuppy** [justinwalsh/daux.io#419]
I have daux running in live mode with the php './serve' command.

I would like to have the search function active and don't mind having to generate to update the search index periodically.

Is there a way to enable the search feature when in this mode?

**Comment by onigoetz** [comment]
Hello,
currently the search is only enabled in generated mode. because the search index would be generated on the file this is not a good option in live mode.

If you want to propose a pull request with a search index that is automatically cached and refreshed, I will merge it, but I don't plan to implement it in the near future.

**Comment by zeigerpuppy** [comment]
Thanks for the details.  For the moment I just implemented an auto-build whenever a file changes (using bash scripts).  It works well for sites like mine that don't change too often.

**Comment by onigoetz** [comment]
Closing this issue as we move the project to an organization: https://github.com/dauxio/daux.io, the packagist package name is now [`daux/daux.io`](https://packagist.org/packages/daux/daux.io) and we even have a [Docker image](https://hub.docker.com/r/daux/daux.io/).

If you are still interested by that feature, please open a new issue in the organization and we'll look into it.
