### ISSUE TITLE
Tipuesearch and Image issues

### ISSUE THREAD

**Issue by Serdaro** [justinwalsh/daux.io#432]
Hello,

While on the desktops it is perfect, search results content exceeds the mobile browser window (we cannot see the whole search result content fit to mobile phone's browser screen size, only the part of it is visible). We tried to look into the CSS file (/tipuesearch/tipuesearch.css) and play with it, but we guess generator does not let the CSS field values to be changed. When we change some values in CSS, it ignores those changes. We would really appreciate any help on how to fix this search result content positioning on mobile browser.

Another minor issue is that some big images are shown squeezed on mobile browsers. Small ones are good both on desktops and mobiles. Any help on this will be much appreciated too.

Thanks a lot.

PS: Thank you so much for this great generator by the way.

**Comment by onigoetz** [comment]
Hello, I made a few enhancements on the search which will come out in the next release.

- The search box doesn't overflow on small screens anymore
- The search box is now correctly centered
- When closing the search, remove the result count from the title
- A small close button appears at the top of the search now

About the images problem, There is a css rule `img { max-width: 100%; }` so that images don't overflow their container. that's why big images appear squeezed.

**Comment by Serdaro** [comment]
@onigoetz , thanks a lot. A dummy question if you don't mind: Do I need to do something extra afterwards, if I download the tag 0.3.2 (in which you fixed this issue)? or do I need to wait for the release?

**Comment by onigoetz** [comment]
Hello, with a `composer global update justinwalsh/daux.io` it should normally take the changes. You're right, it's in the 0.3.2 tag, no specific release needed

**Comment by Serdaro** [comment]
Thanks so much.
