### ISSUE TITLE
[TOC]

### ISSUE THREAD

**Issue by dstrants** [justinwalsh/daux.io#438]
Hello, I try to create a toc in the getting started page but while I am inserting `[TOC]` in the source, there is no toc in the output. Is there any configuration I should have done before inserting the `[TOC]` commands?

**Thanks in advance** 
Dimitris

**Comment by onigoetz** [comment]
Hello,

What version of Daux.io are you using ? did you install it through composer ?

You added the tag at the beginning of the line ?

There is no option to completely disable the TOC option, so if you have the right version of Daux, it should work out of the box

**Comment by onigoetz** [comment]
Closing for non-activity

**Comment by mateusmedeiros** [comment]
I think it's worth clarifying in the docs the fact that the Table of Contents applies to the document itself only, using the header levels to create a tree. Maybe add it to the [Examples](http://daux.io/Examples/index) section or use it in the [Table of Contents](http://daux.io/Features/Table_of_contents) page itself to demonstrate.

The first time I've read the documentation I thought it would generate a table of contents similar to the sidebar one (with the different nesting of document files, instead of headers within a single one). Maybe that's what @dstrants thought too.

When I tried to use that feature for the first time, I thought it's intended use case was those in which people had overriden templates or themes in ways to not show a sidebar at all. When I tried to insert a `[TOC]` in an empty document and nothing appeared, took me quite a while to figure out what was wrong. 😁
