### ISSUE TITLE
High memory usage ends in fatal error

### ISSUE THREAD

**Issue by slackmoehrle** [justinwalsh/daux.io#443]
I am seeing this error, but I don't see a fix.

__Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 64 bytes) in phar://daux.io/daux.phar/libs/Tree/Directory.php on line 51__

Line 51 is a __}__ and I don't see where else this change would make sense.

**Comment by onigoetz** [comment]
Hello, the case of the memory is not necessarily related to a specific line of code.

How big is your documentation ?

**Comment by slackmoehrle** [comment]
Several hundred pages!

________________________________

**Comment by onigoetz** [comment]
Okay, that's probably why, because when creating the documentation it takes all pages in memory and writes them down after.

Is your documentation public by any chance so I can make some tests and improve Daux's behaviour on big projects ?

If not, I will try to replicate your case with dummy pages and hope to get some improvements.

In the meantime, can you try to update to the latest daux version and/or to change your memory parameters ? (`memory_limit` in php.ini)

**Comment by onigoetz** [comment]
Hello @slackmoehrle, sorry for the long wait, I didn't have too much time on side projects these past months. 

I made some improvements in how Daux handles big documentation and their memory usage.

I created a documentation with over 2'700 pages and reduced its memory usage to a minimum. It certainly changes from on documentation to another, but I hope this fix helps you.

You can test it by downloading the latest `dev-master`version in packagist. I hope to be able to make a release of this soon.

**Comment by onigoetz** [comment]
By the way, if you still have problems, you might want to disable the search feature, to generate it, all files have to be kept in memory at the same time, this is one of the main causes of memory usage in the daux generator.

**Comment by slackmoehrle** [comment]
@onigoetz Thanks, I will update my install and test things out.
