### ISSUE TITLE
CSS issues in your docs

### ISSUE THREAD

**Issue by AloeDream** [justinwalsh/daux.io#451]
Pretty much all code blocks in your own docs has incorrect CSS. In Chrome and Edge (latest) it looks like:
![microsoft-edge-web-notes-auto-synt30267328](https://cloud.githubusercontent.com/assets/13584857/25874307/9f8af138-351a-11e7-8b9f-8f6352143950.jpg)

**Comment by eisbehr-** [comment]
I was not sure if this is expected or a bug. But in any way it looks aweful. ;)
Actually I'm searching for a good documentation tool, but this shows actually no quality.

**Comment by mateusmedeiros** [comment]
https://github.com/justinwalsh/daux.io#code-floating

**Comment by AloeDream** [comment]
@mateusmedeiros oh, ok, I see. But I would turn it off anyway, looks not very good.

**Comment by eisbehr-** [comment]
Looks really horrible, to be honest. The feature is not bad, but there are other documentation tools with floating code, which makes this way better. This looks like an error, not like a wanted behavior. There should be some design changes in the future to make this look more consistent ...

**Comment by onigoetz** [comment]
@eisbehr- Not very constructive comment, but I'll take it anyway, thanks for the feedback. do you have an example of tool that has nice code-floating ? I've been trying to improve this feature since i maintain this project. (Personally I'm not a fan of the feature either)

**Comment by eisbehr-** [comment]
@onigoetz Sorry, was not meant to be unconstructive. Maybe it's because I'm not a native speaker and took the wrong words. The problem with daux.io here is easily, that it looks like an error and there is no _line_ or somthing where the eye can find a relation between text and the code box. 

And yes, I have an example. I would say that `flatdoc` did a better job here. It's quite not perfect too, but at least they create a dependency between text and code with some small lines. There is no question that this is wanted and where the code belongs to. 

http://ricostacruz.com/flatdoc/#flatdoc-getting-started-via-github

**Comment by onigoetz** [comment]
No worries :)

Thanks for the link. I will have a look and see how we can improve Daux's implementation.

By the way, I didn't push to master yet. but the latest version has a more modern theme.

**Comment by eisbehr-** [comment]
Looking forward to see this! I actually build a new doc with daux. Maybe I can use it for this! ;)
